name: "Unit Tests"
on:
  push:
    paths:
      - '.github/workflows/units.yml'
      - '**/*.js'
      - '**/*.mjs'
  pull_request:
    paths:
      - '.github/workflows/units.yml'
      - '**/*.js'
      - '**/*.mjs'

jobs:
  # unit tests
  units:
    strategy:
      matrix:
        runs-on: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@master
    - run: npm ci
    - run: npm test
